### PR TITLE
Update XEPs, add Gajim Dev News

### PR DESCRIPTION
**Pull request by wurstsalat3000**
Please don’t merge yet.

### CODE REVIEW

**Comment by Echolon** [comment]
Okay, please mention me, once you are ready.

Thank you for your work. It is really helpful!

**Comment by wurstsalat3000** [comment]
@Echolon now it’s ok to be merged!

**Comment by Echolon** [comment]
Lift off! :rocket:

**Comment by Echolon** [comment]
Thank you very much - highly appreciated!

**Pull request merged**
